/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package juegozombies;

import javax.swing.JOptionPane;

/**
 *
 * @author josem
 */
public class VentanaAtacarObjetivo extends javax.swing.JFrame {
    private EArmas arma;
    private Superviviente jugador = Juego.obtenerJugadorActual();
    
    /**
     * Creates new form VentanaAtacarObjetivo
     */
    public VentanaAtacarObjetivo(EArmas arma) {
        this.arma = arma;
        initComponents();
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ObjetivoX = new javax.swing.JTextField();
        ObjetivoY = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        aceptar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        ObjetivoX.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ObjetivoXMouseClicked(evt);
            }
        });
        ObjetivoX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ObjetivoXActionPerformed(evt);
            }
        });

        ObjetivoY.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ObjetivoYMouseClicked(evt);
            }
        });
        ObjetivoY.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ObjetivoYActionPerformed(evt);
            }
        });

        jLabel1.setText("Introduce la X");

        jLabel2.setText("Introduce la Y");

        jLabel3.setText("Elige la casilla a la que disparar:");

        aceptar.setText("Aceptar");
        aceptar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                aceptarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ObjetivoX))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(ObjetivoY)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel3)))
                .addContainerGap(18, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(aceptar)
                .addGap(62, 62, 62))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ObjetivoY, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ObjetivoX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(aceptar)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ObjetivoXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ObjetivoXActionPerformed

    }//GEN-LAST:event_ObjetivoXActionPerformed

    private void ObjetivoYActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ObjetivoYActionPerformed

    }//GEN-LAST:event_ObjetivoYActionPerformed

    private void ObjetivoXMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ObjetivoXMouseClicked
        // TODO add your handling code here:

            

       
        //jugador.obtenerCasillaObjX(x);
        //setVisible(false);
    }//GEN-LAST:event_ObjetivoXMouseClicked

    private void ObjetivoYMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ObjetivoYMouseClicked
        // TODO add your handling code here:
        //Superviviente jugador = Juego.obtenerJugadorActual();
        //int y = Integer.parseInt(ObjetivoY.getText());
        //jugador.obtenerCasillaObjY(y);
        //setVisible(false);
    }//GEN-LAST:event_ObjetivoYMouseClicked

    private void aceptarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_aceptarMouseClicked
        Superviviente jugador = Juego.obtenerJugadorActual();
        int x = Integer.parseInt(ObjetivoX.getText());
        int y = Integer.parseInt(ObjetivoY.getText());
        double distancia = Math.sqrt(((x - jugador.devolverCoordenada().getX())^2) + ((y-jugador.devolverCoordenada().getY())^2));
        if((x>Juego.getTamanoCuadricula().getX()-1 || x<0) || (y>Juego.getTamanoCuadricula().getY()-1 || y<0)){
           JOptionPane.showMessageDialog(null, "Fuera de los límites ", "¡ADVERTENCIA!" , JOptionPane.WARNING_MESSAGE); 
        }else if  (distancia > arma.getAlcanceMax()){  
           JOptionPane.showMessageDialog(null, "Fuera del alcance del arma ", "¡ADVERTENCIA!" , JOptionPane.WARNING_MESSAGE); 
        }else{
            this.dispose();
            jugador.atacar(x, y, arma);
             
             // falta implementarlo para atacar y que se hagan bien los turnos
        }   
    }//GEN-LAST:event_aceptarMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ObjetivoX;
    private javax.swing.JTextField ObjetivoY;
    private javax.swing.JButton aceptar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
