/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package juegozombies;

import java.awt.BorderLayout;
import javax.swing.JComboBox;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author josem
 */
public class VentanaAtacarElegirArma extends javax.swing.JFrame {
        JFrame frame = new JFrame();
        JPanel panel = new JPanel();
        Superviviente jugador = Juego.obtenerJugadorActual();
        JComboBox<EArmas>armas;
        EArmas opciones[];
    /**
     * Creates new form VentanaAtacarElegirArma
     */
    public VentanaAtacarElegirArma() {
        try{
            opciones = new EArmas[jugador.armasActivas.size()];
            for(int i=0; i<jugador.armasActivas.size(); i++){
                opciones[i] = jugador.armasActivas.get(i);
            }
        }catch (NullPointerException e) {
            // Manejo de la excepción
            JOptionPane.showMessageDialog(null, "El superviviente no tiene armas", "¡ADVERTENCIA!" , JOptionPane.WARNING_MESSAGE);    
        }
        armas = new JComboBox<>(opciones);
        frame.setTitle("VentanaJuego");
        frame.setSize(200, 300);
        frame.setResizable(true);
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        panel.add(armas);
        frame.add(panel, BorderLayout.CENTER);
        frame.setVisible(true);
    }
    private void armasActionPerformed(java.awt.event.ActionEvent evt) {                                          
        // TODO add your handling code here:

        setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
